- name: Deny access to port 4000
  ufw:
    rule: deny
    port: 4000

- name: Allow access to ports
  ufw:
    rule: allow
    port: "{{item}}"
  with_items:
    - 22
    - 80
    - 443
    - 1935
    - 8080

- name: Enable firewall
  ufw:
    state: enabled

